// GENERATED by tools/gen_assets.py -- do not edit.
// Source images live in assets/.

#ifndef ASSETS_DATA_H
#define ASSETS_DATA_H

#include <stddef.h>
#include <stdint.h>

extern const uint8_t asset_test_chart_png[];
extern const size_t asset_test_chart_png_len;

extern const uint8_t asset_test_photo_jpg[];
extern const size_t asset_test_photo_jpg_len;

extern const uint8_t asset_test_small_bmp[];
extern const size_t asset_test_small_bmp_len;

extern const uint8_t asset_index_html_gz[];
extern const size_t asset_index_html_gz_len;

#endif // ASSETS_DATA_H
