// The public half of the key that signs Google Photos scrape rules.
//
// Generated by tools/gphotos_rules_sign.py keygen. The private half is not in this
// repository. A rule file that does not verify against this key is never used
// (src/app_gphotos_rules.h), so replacing it means a reflash of every frame.

#ifndef GPHOTOS_RULES_PUBKEY_H
#define GPHOTOS_RULES_PUBKEY_H

static const char GPHOTOS_RULES_PUBKEY_PEM[] =
    "-----BEGIN PUBLIC KEY-----\n"
    "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE8xgMjM1xHDZXpbhqNPYNJjw92fap\n"
    "+vgfBqQRajFYCF2h6uX1fYCM79j1Jh5QMEWwG5C3OyCycdgNWkjluEpgWg==\n"
    "-----END PUBLIC KEY-----\n";

#endif // GPHOTOS_RULES_PUBKEY_H
