#!/usr/bin/env python3
"""Turn assets/ into a C source file of byte arrays.

Embedding binaries ought to be the build system's job, and under plain ESP-IDF it is --
`EMBED_FILES` in CMakeLists. Under PlatformIO it is not:

  * CMake's `EMBED_FILES` makes PlatformIO's SCons layer look for a generated assembly
    stub it never finds -- "Source `.pio\\build\\photo\\test-chart.png.S' not found".
  * PlatformIO's own `board_build.embed_files` takes the espidf branch of
    platforms/espressif32/builder/frameworks/_embed_files.py, which calls
    `env.FileToAsm(...)` to *generate* the .S and then never adds it to the build.
    The link fails with undefined `_binary_*` symbols.

So the bytes are turned into C here instead, where nothing can go wrong quietly.

    python tools/gen_assets.py

Writes src/app/assets_data.c and src/app/assets_data.h. Both are generated -- edit this
script, not them. The destination is src/app/ and not src/ because src/CMakeLists.txt
globs src/*.c recursively: a copy left in src/ compiles alongside the one in src/app/ and
the link fails on duplicate symbols.
"""

import gzip
import pathlib
import sys

REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent
ASSET_DIR = REPO_ROOT / "assets"
OUT_C = REPO_ROOT / "src" / "app" / "assets_data.c"
OUT_H = REPO_ROOT / "src" / "app" / "assets_data.h"

# filename -> C identifier stem
ASSETS = {
    "test-chart.png": "asset_test_chart_png",
    "test-photo.jpg": "asset_test_photo_jpg",
    "test-small.bmp": "asset_test_small_bmp",
}

# Embedded gzipped, and served with Content-Encoding: gzip, which is the difference between a page
# that loads over the softAP and one that crawls. It is ported byte for byte -- reimplementing it
# would cost more than the rest of the frame, and ticket 65 item 4 is where that is being weighed.
#
# **Every size figure written into this comment has gone stale, so read the one this script PRINTS
# instead.** It said 139 KB raw / ~30 KB gzipped, then 206,231 / 52,937 at 2026-09-18, and at
# 2026-09-21 it is **313,759 B raw gzipped to 86,831 B** — ticket 74 added `ja` and `zh-TW`
# dictionaries, +26,076 B of flash and zero bytes of RAM. The line above the array in the generated
# `assets_data.c` carries the current pair, which is why that line exists.
#
# Re-measure rather than quote, and mind WHICH figure you have: `gzip -c assets/index.html | wc -c`
# and this script disagree by ~100 B, because the script uses level 9 with `mtime=0`. The served
# figure is the script's, and `curl --compressed <frame>/ -o /dev/null -w '%{size_download}'` is how
# you read it off a device. Calling a `gzip -c` number "served" put a 106 B error in ticket 74.
GZIP_ASSETS = {
    "index.html": "asset_index_html_gz",
}

BANNER = ("// GENERATED by tools/gen_assets.py -- do not edit.\n"
          "// Source images live in assets/.\n\n")


def main():
    missing = [n for n in list(ASSETS) + list(GZIP_ASSETS)
               if not (ASSET_DIR / n).is_file()]
    if missing:
        sys.exit(f"missing assets: {', '.join(missing)}")

    h = [BANNER, "#ifndef ASSETS_DATA_H\n#define ASSETS_DATA_H\n\n",
         "#include <stddef.h>\n#include <stdint.h>\n\n"]
    c = [BANNER, '#include "assets_data.h"\n\n']

    total = 0
    items = [(n, s, False) for n, s in ASSETS.items()]
    items += [(n, s, True) for n, s in GZIP_ASSETS.items()]
    for name, stem, compress in items:
        raw = (ASSET_DIR / name).read_bytes()
        data = gzip.compress(raw, 9, mtime=0) if compress else raw
        total += len(data)

        h.append(f"extern const uint8_t {stem}[];\n")
        h.append(f"extern const size_t {stem}_len;\n\n")

        note = f", {len(raw)} bytes gzipped to {len(data)}" if compress else f", {len(data)} bytes"
        c.append(f"// {name}{note}\n")
        c.append(f"const uint8_t {stem}[] = {{\n")
        for i in range(0, len(data), 16):
            row = ",".join(f"0x{b:02x}" for b in data[i:i + 16])
            c.append(f"    {row},\n")
        c.append("};\n")
        c.append(f"const size_t {stem}_len = sizeof({stem});\n\n")

    h.append("#endif // ASSETS_DATA_H\n")

    OUT_H.write_text("".join(h), encoding="utf-8")
    OUT_C.write_text("".join(c), encoding="utf-8")
    print(f"{OUT_H}\n{OUT_C}\n{total} bytes of assets")


if __name__ == "__main__":
    main()
